# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lexseal/Documents/sudoku

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lexseal/Documents/sudoku

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lexseal/Documents/sudoku/CMakeFiles /home/lexseal/Documents/sudoku/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lexseal/Documents/sudoku/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sudoku

# Build rule for target.
sudoku: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sudoku
.PHONY : sudoku

# fast build rule for target.
sudoku/fast:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/build
.PHONY : sudoku/fast

imgToNum.o: imgToNum.cpp.o

.PHONY : imgToNum.o

# target to build an object file
imgToNum.cpp.o:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/imgToNum.cpp.o
.PHONY : imgToNum.cpp.o

imgToNum.i: imgToNum.cpp.i

.PHONY : imgToNum.i

# target to preprocess a source file
imgToNum.cpp.i:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/imgToNum.cpp.i
.PHONY : imgToNum.cpp.i

imgToNum.s: imgToNum.cpp.s

.PHONY : imgToNum.s

# target to generate assembly for a file
imgToNum.cpp.s:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/imgToNum.cpp.s
.PHONY : imgToNum.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/main.cpp.s
.PHONY : main.cpp.s

solver.o: solver.cpp.o

.PHONY : solver.o

# target to build an object file
solver.cpp.o:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/solver.cpp.o
.PHONY : solver.cpp.o

solver.i: solver.cpp.i

.PHONY : solver.i

# target to preprocess a source file
solver.cpp.i:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/solver.cpp.i
.PHONY : solver.cpp.i

solver.s: solver.cpp.s

.PHONY : solver.s

# target to generate assembly for a file
solver.cpp.s:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/solver.cpp.s
.PHONY : solver.cpp.s

sudokuBoard.o: sudokuBoard.cpp.o

.PHONY : sudokuBoard.o

# target to build an object file
sudokuBoard.cpp.o:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/sudokuBoard.cpp.o
.PHONY : sudokuBoard.cpp.o

sudokuBoard.i: sudokuBoard.cpp.i

.PHONY : sudokuBoard.i

# target to preprocess a source file
sudokuBoard.cpp.i:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/sudokuBoard.cpp.i
.PHONY : sudokuBoard.cpp.i

sudokuBoard.s: sudokuBoard.cpp.s

.PHONY : sudokuBoard.s

# target to generate assembly for a file
sudokuBoard.cpp.s:
	$(MAKE) -f CMakeFiles/sudoku.dir/build.make CMakeFiles/sudoku.dir/sudokuBoard.cpp.s
.PHONY : sudokuBoard.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sudoku"
	@echo "... imgToNum.o"
	@echo "... imgToNum.i"
	@echo "... imgToNum.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... solver.o"
	@echo "... solver.i"
	@echo "... solver.s"
	@echo "... sudokuBoard.o"
	@echo "... sudokuBoard.i"
	@echo "... sudokuBoard.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

